name: Deploy Zsazsa Blog

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Siapkan Docker
        run: docker build -t zsazsa-blog .
